// Generated by CoffeeScript 1.6.3
(function() {
  var db;

  db = require('./db')("" + __dirname + "/../db/test");

  module.exports = {
    log: function(login, password, callback) {
      var rs, userinfo;
      console.log("LOG CALLED");
      console.log(login);
      console.log(password);
      userinfo = [];
      rs = db.createReadStream({
        start: "user:" + login + ":",
        end: "user:" + login + ";"
      });
      rs.on('data', function(data) {
        var mailDB, passwordDB, _ref;
        console.log("Data found");
        _ref = data.value.split(':'), mailDB = _ref[0], passwordDB = _ref[1];
        userinfo.push({
          login: login,
          password: passwordDB,
          mail: mailDB
        });
        console.log(login);
        return console.log(passwordDB);
      });
      rs.on('error', callback);
      return rs.on('close', function() {
        return callback(null, userinfo);
      });
    },
    save: function(login, mail, password, callback) {
      var ws;
      ws = db.createWriteStream();
      ws.on('error', callback);
      ws.on('close', callback);
      ws.write({
        key: "user:" + login,
        value: "" + mail + ":" + password
      });
      return ws.end();
    }
  };

}).call(this);
